version: '3.9'
name: 'hayat_cable'

networks:
  dev:

x-base-project: &base-project
  env_file:
    - .env
  volumes:
    - ./project:/opt/project
  build:
    context: .
    dockerfile: Dockerfile
    target: local

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - project
      - postgres-db
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './ssl-certificate/:/etc/letsencrypt/live/'
      - static_volume:/static
    networks:
      - dev
  project:
    <<: *base-project
    command: ["make", "run_server"]
    depends_on:
      - postgres-db
    ports:
      - ${LOCAL_IP:-127.0.0.1}:${API_LOCAL_PORT:-8000}:8000
    networks:
      - dev

  postgres-db:
    environment:
      POSTGRES_USER: hayat_cable_user
      POSTGRES_DB: hayat_cable_db
      POSTGRES_PASSWORD: hayat_cable_password
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    networks:
      - dev

volumes:
  static_volume:
  pg_data: {}
