# Generated by Django 5.0 on 2025-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutusmodel_goalmodel_calendarmodel_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmodel',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
    ]
