# Generated by Django 5.0 on 2025-02-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_calendarmodel_country_code'),
        ('home', '0003_gallerymodel_gallerymodeltranslation'),
    ]

    operations = [
    ]
