# Generated by Django 5.0 on 2025-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_commandmodel_eventcalendarmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmodeltranslation',
            name='position',
            field=models.CharField(choices=[('M', 'Management'), ('C', 'Committee'), ('P', 'Presidium')], max_length=1, verbose_name='Position'),
        ),
    ]
