# Generated by Django 5.0 on 2025-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_commandmodeltranslation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandmodeltranslation',
            name='federation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Federation'),
        ),
        migrations.AddField(
            model_name='commandmodeltranslation',
            name='responsibility',
            field=models.CharField(default='a', max_length=32, verbose_name='Responsibility'),
            preserve_default=False,
        ),
    ]
