# Generated by Django 5.0 on 2025-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_commandmodeltranslation_federation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandmodeltranslation',
            name='position',
        ),
        migrations.AddField(
            model_name='commandmodel',
            name='position',
            field=models.CharField(choices=[('M', 'Management'), ('C', 'Committee'), ('P', 'Presidium')], default='M', max_length=1, verbose_name='Position'),
        ),
    ]
